#! /usr/bin/env python2

"""DESCRIPTION
"""

import sys
import argparse
from gi.repository import GLib
import dbus
from dbus.mainloop.glib import DBusGMainLoop

def quitter(loop):
    def _quit(*args, **kwargs):
        loop.quit()
    return _quit

def main(options):
    """Main program."""
    DBusGMainLoop(set_as_default=True)
    system_bus = dbus.SystemBus()
    systemd1 = system_bus.get_object('org.freedesktop.systemd1', '/org/freedesktop/systemd1')
    systemd1_iface = dbus.Interface(systemd1, dbus_interface='org.freedesktop.systemd1.Manager')
    loop = GLib.MainLoop()
    signals = ('UnitNew',
               'UnitRemoved',
               'JobNew',
               'JobRemoved',
               'UnitFilesChanged',
               'StartupFinished',
               'Reloading')
    for sig in signals:
        systemd1.connect_to_signal(sig, quitter(loop))
    loop.run()
    return

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
        description="DESCRIPTION",
    )
    # parser.add_argument() calls here
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())
